### ISSUE TITLE
Can't use "transforms" module in typescript

### ISSUE THREAD

**Issue by thosil** [yusufsaygili/signalprocessing#2]
Hello,

first thanks for the lib!

I tried to use it within a typescript project and had this issue:
```
> tsc

node_modules/@signalprocessing/transforms/declarations/transforms.d.ts:11:25 - error TS2300: Duplicate identifier 'inputReal'.

11     export function fft(inputReal:number[],inputReal?:number[]):number[][]
                           ~~~~~~~~~

node_modules/@signalprocessing/transforms/declarations/transforms.d.ts:11:44 - error TS2300: Duplicate identifier 'inputReal'.

11     export function fft(inputReal:number[],inputReal?:number[]):number[][]
                                              ~~~~~~~~~
```

It looks like it's just a typo in the transforms.d.ts file.
I created a PR to fix it: #1 

Thanks

**Comment by yusufsaygili** [comment]
Dear Thomas,

Thank you for your feedback. 

I just fixed the issue. 

It was the first issue in the coding history of me. :)

If you suggest anything, I will be appreciated.

Regards

Yusuf
