### ISSUE TITLE
Package not available anymore in npmjs

### ISSUE THREAD

**Issue by davidlilien** [yusufsaygili/signalprocessing#4]
Hi,

Just noticed that this package is not available anymore on npmjs repo

`npm install @signalprocessing/transforms --save`

--> 404

Any clues ?

**Comment by yusufsaygili** [comment]
Hello David,

I just deprecated it and replaced it with new package called runform.  
if you want to use fft and ifft, you may use the "runform" npm package.

Regards
Yusuf

Alıntı David Lilien ***@***.***>:

**Comment by davidlilien** [comment]
Thanks for the quick response
